INSERT  INTO
	work_user
      ( 
      ID                            
      ,phone                          
      ,username                       
      ,password                       
      ,status                         
      ,userkey                        
      ,idcard                         
      ,realname                       
      ,sex                            
      ,address    
      ,usertype
      ,openid
      ,xcxid
      ) 
values
      (
      :workUser.id                            
      ,:workUser.phone                         
      ,:workUser.username                      
      ,:workUser.password                      
      ,:workUser.status                        
      ,:workUser.userkey                       
      ,:workUser.idcard                        
      ,:workUser.realname                      
      ,:workUser.sex                           
      ,:workUser.address  
      ,:workUser.usertype
      ,:workUser.openid
      ,:workUser.xcxId
      )