INSERT  INTO
	work_guide
      ( 
      id         
      ,guide_name
      ,item_type                      
      ,nature                      
      ,management                     
      ,work_code                      
      ,address                        
      ,phone                          
      ,audit                          
      ,office_type                    
      ,work_time                      
      ,legal_time                     
      ,promise_time                   
      ,result_name                    
      ,work_type                      
      ,work_level                     
      ,num_limit                      
      ,fee_type                       
      ,domain                         
      ,agency                         
      ,admissibility                  
      ,foundation                     
      ,fee_scale                      
      ) 
values
      (
      :workGuide.id         
      ,:workGuide.guideName
      ,:workGuide.itemType                      
      ,:workGuide.nature                     
      ,:workGuide.management                    
      ,:workGuide.workCode                      
      ,:workGuide.address                       
      ,:workGuide.phone                         
      ,:workGuide.audit                         
      ,:workGuide.officeType                    
      ,:workGuide.workTime                      
      ,:workGuide.legalTime                     
      ,:workGuide.promiseTime                   
      ,:workGuide.resultName                    
      ,:workGuide.workType                      
      ,:workGuide.workLevel                     
      ,:workGuide.numLimit                      
      ,:workGuide.feeType                       
      ,:workGuide.domain                        
      ,:workGuide.agency                        
      ,:workGuide.admissibility                 
      ,:workGuide.foundation                    
      ,:workGuide.feeScale                      
      )